TH-574. Fix log messages.
th2-net/th2-act-template-j pull request #3
Opened 2020-11-26 12:05 UTC by miffn3

2020-11-26 16:28 UTC, jean-michel-perli-sonsin requested changes

2020-11-26 16:28 UTC, jean-michel-perli-sonsin commented on src/main/java/com/exactpro/th2/act/ActHandler.java
> +            logger.debug("Sending message has been finished in {}", System.currentTimeMillis() - startPlaceMessage);
Sending **the** message has been finished in

2020-11-26 16:28 UTC, jean-michel-perli-sonsin commented on src/main/java/com/exactpro/th2/act/ActHandler.java
> +                    sendErrorResponse(responseObserver, "Request has been cancelled by client");
**The** request has been cancelled by **the** client

2020-11-26 16:28 UTC, jean-michel-perli-sonsin commented on src/main/java/com/exactpro/th2/act/ActHandler.java
> +            logger.debug("Sending a message started");
Sending **the** message started

2020-11-26 16:28 UTC, jean-michel-perli-sonsin commented on src/main/java/com/exactpro/th2/act/ActHandler.java
> +            logger.debug("Sending a message ended");
Sending **the** message started

2020-11-26 16:28 UTC, jean-michel-perli-sonsin commented on src/main/java/com/exactpro/th2/act/ActHandler.java
> +        logger.debug("Registering a checkpoint start");
Registering **the** checkpoint **started**

2020-11-26 16:28 UTC, jean-michel-perli-sonsin commented on src/main/java/com/exactpro/th2/act/ActHandler.java
> +            logger.debug("Registering a checkpoint ended. Response " + shortDebugString(response));
Registering **the** checkpoint ended

2020-11-27 15:26 UTC, Nikita-Smirnov-Exactpro approved these changes

2020-11-30 18:41 UTC, merged